[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--capture=tee-sys -p no:warnings --dj-teardown False --dj-verbose True --sw --cov=element_array_ephys --cov-report term-missing"
# Verbosity: -v for pytest more verbose
# Warnings: -p no:warnings to disable
# Stepwise: --sw to restart pytest at last failure point
# Debug: --pdb enter debug mode on first failure
# Capturing output: -s for none, --capture=tee-sys for both stdout and stderr
# Coverage: --cov={package} - package for which we're measuring coverage
# Coverage report: --cov-report term-missing send report to stdout with line numbers of missed
# Custom teardown: --dj-teardown {True, False} to teardown tables,
# Custom verbose: --dj-verbose {True,False} print out dj info like table inserts
testpaths = [
    "tests",
]
norecursedirs = ["docs", "*.egg-info", ".git"]
# PYTHONDONTWRITEBYTECODE=1 # Setting this env variable will speed up pytest
